services:
  app:
    image: poofeg/vk-to-commerceml
    environment:
      BOT_TOKEN:
      BASE_URL:
      VK__OAUTH_CALLBACK_URL:
      VK__CLIENT_ID:
      VK__CLIENT_SECRET:
      REDIS_URL: redis://redis/0
      ENCRYPTION_KEY:
      CML_DEBUG_BASE_PATH:

    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
